# Generated by Django 3.0.6 on 2020-05-13 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=6)),
                ('created_date', models.DateTimeField(verbose_name='date Created')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 8, 30, 59, 600610, tzinfo=utc), verbose_name='date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='LiquorStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(default=uuid.UUID('5d7d9f2b-ec77-4dc2-8337-934ae54d84a0'), max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(verbose_name='date Created')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 8, 30, 59, 626327, tzinfo=utc), verbose_name='date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('created_date', models.DateTimeField(verbose_name='date Created')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 8, 30, 59, 625850, tzinfo=utc), verbose_name='date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.CharField(max_length=1000)),
                ('token_valid', models.BooleanField(default=False)),
                ('token_slot', models.CharField(max_length=1000)),
                ('pickup_date', models.DateTimeField(verbose_name='Pickup Date')),
                ('token_created', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 8, 30, 59, 626997, tzinfo=utc), verbose_name='Token created')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquor.Consumer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquor.LiquorStore')),
            ],
        ),
        migrations.AddField(
            model_name='liquorstore',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquor.StoreOwner'),
        ),
    ]
