# Generated by Django 3.0.6 on 2020-05-09 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquorstore',
            name='token_date',
        ),
        migrations.AddField(
            model_name='liquorstore',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeownmer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='created_date',
            field=models.DateTimeField(verbose_name='date Created'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
