# Generated by Django 3.0.6 on 2020-05-09 04:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0002_auto_20200509_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('created_date', models.DateTimeField(verbose_name='date Created')),
                ('updated_date', models.DateTimeField(verbose_name='date Updated')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='pincode',
            field=models.CharField(default=332024, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 16, 11, 21, 462964), verbose_name='date Updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquorstore',
            name='pincode',
            field=models.CharField(default=332024, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 16, 11, 56, 677443), verbose_name='date Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquor.StoreOwner'),
        ),
        migrations.DeleteModel(
            name='StoreOwnmer',
        ),
    ]
