# Generated by Django 3.0.6 on 2020-05-09 05:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0003_auto_20200509_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_date',
        ),
        migrations.AddField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 17, 9, 15, 348716), verbose_name='Token created'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 17, 9, 15, 295982), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=uuid.UUID('03840df4-331b-4ae6-ad7f-8adb77a71c91'), max_length=200),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 17, 9, 15, 348716), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 17, 9, 15, 347744), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_valid',
            field=models.BooleanField(default=False),
        ),
    ]
