# Generated by Django 3.0.6 on 2020-05-09 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0006_auto_20200509_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_slot',
            field=models.CharField(default='00:00', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 14, 2, 47, 209049, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=uuid.UUID('73b3c8f2-b720-417f-87d5-455c2a596f18'), max_length=200),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 14, 2, 47, 257816, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 14, 2, 47, 257816, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 14, 2, 47, 258791, tzinfo=utc), verbose_name='Token created'),
        ),
    ]
