# Generated by Django 3.0.6 on 2020-05-09 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0007_auto_20200510_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 15, 15, 38, 991858, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=uuid.UUID('757d8570-25e7-4342-8993-bf1e02d84f45'), max_length=200),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 15, 15, 39, 52371, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 15, 15, 39, 51395, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 15, 15, 39, 52371, tzinfo=utc), verbose_name='Token created'),
        ),
    ]
