# Generated by Django 3.0.6 on 2020-05-09 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0008_auto_20200510_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pickup_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 11, 42, 54, 657397), verbose_name='Pickup Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 23, 42, 38, 661783, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=uuid.UUID('573651a0-ba38-4e94-9e6f-efb6341c2a6f'), max_length=200),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 23, 42, 38, 705262, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 23, 42, 38, 704762, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 23, 42, 38, 705765, tzinfo=utc), verbose_name='Token created'),
        ),
    ]
