# Generated by Django 3.0.6 on 2020-05-10 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0009_auto_20200510_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 36, 37, 398917, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=uuid.UUID('30acb6cd-9df3-4722-b815-de7aa71430aa'), max_length=200),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 36, 37, 437991, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 36, 37, 437490, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 1, 36, 37, 437991, tzinfo=utc), verbose_name='Token created'),
        ),
    ]
