# Generated by Django 3.0.6 on 2020-05-10 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liquor', '0010_auto_20200510_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 4, 49, 11, 106379, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='store_id',
            field=models.CharField(default=uuid.UUID('d2d45a72-9aba-4a50-81fa-f48c8e8fb6a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='liquorstore',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 4, 49, 11, 146615, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 4, 49, 11, 146615, tzinfo=utc), verbose_name='date Updated'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 4, 49, 11, 146615, tzinfo=utc), verbose_name='Token created'),
        ),
    ]
